### ISSUE TITLE
Benchmarking crashes in sharrow `compile`

### ISSUE THREAD

**Issue by i-am-sijia** [ActivitySim/activitysim-prototype-mtc#15]
When I attempted to run MTC benchmarking with the latest ActivitySim and Sharrow, it crashed in the sharrow compile mode. Complaining about utility not matching. I tried again from a fresh installation, it crashed at the same point.

To replicate:
- ActivitySim: pr/867@c9d420550 (the latest as of today)
- Sharrow: v2.10.0 (the latest as of today)
- Get example data using: https://github.com/ActivitySim/activitysim-prototype-mtc?tab=readme-ov-file#installation
- set `chunk_training_mode: disabled` in performance-benchmarking.yaml 
- Running benchmarking using: https://github.com/ActivitySim/activitysim-prototype-mtc?tab=readme-ov-file#installation

![image](https://github.com/ActivitySim/activitysim-prototype-mtc/assets/28812722/f36156b4-7448-47a5-8035-f4a691e882fb)

[activitysim.log](https://github.com/user-attachments/files/15992241/activitysim.log)

**Comment by jpn--** [comment]
This error occurred due to the `atol` parameter on the check being set to `0`.  We can see in the output the max absolute difference is only 3.278e-07, which is quite small but not actually zero.  So in https://github.com/ActivitySim/activitysim/pull/878 I have adjusted the default `atol` parameter on these checks in ActivitySim to 1e-06.  I have run this same test per the notes above and I now see no error.
